### ISSUE TITLE
La aplicación no se inicia (SiembrasMiantioquia_PoC_NoSQL_Console)

### ISSUE THREAD

**Issue by Galhrrera** [jdrodas/SiembrasMiantioquia#10]
No hay código en el método **main** de la aplicación en la clase program.cs, por lo que no hay nada que se ejecute.

**Comment by jdrodas** [comment]
Gracias @Galhrrera por el issue.

Inicialmente comenzamos el proyecto con la construcción de la capa de acceso a datos para proceder a verificar cada una de las funcionalidades CRUD.

He actualizado el proyecto con una consulta inicial. El resto de las acciones crud las realizaremos en clase.
