### ISSUE TITLE
Bug -  el código es errado cuando se crea una nueva siembra

### ISSUE THREAD

**Issue by LuhBello** [jdrodas/SiembrasMiantioquia#11]
Cuando se registra una nueva siembra, el código es 0, puede que siempre.

**Comment by LuhBello** [comment]
Lee el código predeterminado.

**Comment by jdrodas** [comment]
Gracias @LuhBello por el reporte.

Efectivamente, cuando se registra una nueva siembra, la propiedad "Codigo_Siembra" queda con el valor predeterminado "0", ya que no se tiene habilitada la funcionalidad de autonumérico para este campo. A nivel de base de datos está registrando asi:

![image](https://user-images.githubusercontent.com/29258977/197555016-f8592dc2-bf88-4227-a2bc-e9e78e9d6b81.png)

Este issue quedará como el principal de este bug. Los otros estarán siendo referenciados aqui.

**Comment by jdrodas** [comment]
Hola! Este es el detalle de la solución implementada, pero antes un tres observaciones:

**Observaciones**

1. Todos los documentos en MongoDB ya tienen un consecutivo único en el campo "_id". Otra cosa es que sea imposible de memorizar, **pero ese valor no debería ser visible para el usuario en su UI**. Este ObjectId permite garantizar unicidad y concurrencia en todas las instancias cuando se implementa modelos de replicación para garantizar alta disponibilidad.

2. Es posible "simular" una secuencia de la misma manera en que lo hacen DB como SQLite, guardando esa información en una tabla aparte; en nuestro caso sería una colección aparte. Esta implementación rompe integridad referencial al momento de replicar en diferentes nodos, pues cada uno de ellos tiene una copia de la colección de Contadores y por lo tanto lo puede manipular independientemente según sea su necesidad. **Esta práctica no es recomendable.**

3. La lógica para leer y actualizar el consecutivo debería implementarse directamente en la aplicación como parte de su capa de acceso a datos (DAL) y no implementar lógica almacenada directamente en la base de datos. **Esta práctica no es recomendable**

Para propósitos académicos, una solución que nos funciona en nuestro ambiente de aprendizaje sería el siguiente. Para casos de implementación en producción, te invito a consultar las opciones avaladas por el fabricante para este propósito o ... o... o ... **CAMBIAR LA APLICACIÓN PARA QUE NO NECESITE AUTOINCREMENTALES**

**Pasos:**

1. Seleccione la DB y cree la colección "Contadores". Inserte un documento por cada consecutivo que quiera gestionar de esta forma:

![image](https://user-images.githubusercontent.com/29258977/197877054-5bf50171-e260-46b1-b3f9-39ee39df1c5b.png)

2. Verifique los valores de cada contador y ajuste según la cantidad de documentos de esa entidad. Por ejemplo, Siembras va en 2, el siguiente valor será 3:

![image](https://user-images.githubusercontent.com/29258977/197877659-284f28c9-385d-41e3-9086-9d6c6380f595.png)

3. En el proyecto, Cree una clase "Contador" para manipular esta colección:

![image](https://user-images.githubusercontent.com/29258977/197877790-d3b3b8d4-ecaa-46cf-b378-23398b533ed9.png)

4. En el proyecto, cree un método privado para obtener el siguiente valor del contador según la entidad/colección:

![image](https://user-images.githubusercontent.com/29258977/197878029-3ccbd877-1a69-428d-80fb-45a9fff55c2a.png)

5. Finalmente, en el proyecto, en el método de guardar la entidad/colección, invoque el consecutivo para asignárselo al objeto antes de ser insertado en la base de datos:

![image](https://user-images.githubusercontent.com/29258977/197878302-db8be616-0106-41f3-8f94-c17e030fb009.png)
 
De manera similar se podrá obtener el consecutivo para el resto de las colecciones de la aplicación.
