### ISSUE TITLE
codigo 0 al agregar una nueva siembra

### ISSUE THREAD

**Issue by gabilang12** [jdrodas/SiembrasMiantioquia#12]

**Comment by jdrodas** [comment]
Gracias @gabilang12 por tu reporte!

Lo estaremos resolviendo en conjunto con el incidente #13

**Comment by jdrodas** [comment]
Hola @gabilang12 !

La documentación del bug la estamos trabajando en el incidente #11 . Cerraré este issue y nos enfocaremos en el otro.
