### ISSUE TITLE
El programa permite ingresar total de arboles como cero o negativos.

### ISSUE THREAD

**Issue by 018monroz** [jdrodas/SiembrasMiantioquia#16]
La aplicación debe impedir el ingreso de datos del total de arboles en cero, ya que tiene poco sentido que se registre una siembra sin arboles: o en negativos, ya que físicamente esto es imposible.

![image](https://user-images.githubusercontent.com/71842389/201760966-afc64444-3e38-4997-9316-6f67d14a5c7e.png)
Vista desde la aplicación
![image](https://user-images.githubusercontent.com/71842389/201760984-3212bea7-276d-4699-adf8-2232acf3a3a4.png)
Vista desde MongoDB Compass
![image](https://user-images.githubusercontent.com/71842389/201761036-56d1dc5f-35e2-4930-8658-7253486559c0.png)

**Comment by jdrodas** [comment]
Gracias @018monroz  por el reporte.

Se implementó control para evitar que se registren nuevas siembras con total de árboles como cero o negativos. El control se visualiza de la siguiente manera:

![image](https://user-images.githubusercontent.com/29258977/205189734-d641be81-534e-4d03-b3f3-f0107f10f227.png)

Se implementa controles adicionales en los métodos "ValidaDatosNuevaSiembra" y "ValidaDatosSiembraActualizada" en cada una de las formas "FormaNuevaSiembra" y "FormaActualizaSiembra" para evitar este comportamiento erróneo.
