### ISSUE TITLE
El programa permite ingresar hectáreas de siembra como cero o negativos.

### ISSUE THREAD

**Issue by 018monroz** [jdrodas/SiembrasMiantioquia#19]
Cuando se realiza una siembra, es imposible que no ocupe espacio físico rural para su cosecha (No puede ser un valor cero). Es incluso aún más imposible que una siembra ocupe espacio físico negativo (Es como si se hubieran sembrado en un no-espacio o en otra dimensión).
La aplicación deberá impedir el ingreso de valores de cero o negativos en el espacio de total hectáreas.

![image](https://user-images.githubusercontent.com/71842389/201761913-a4c358bb-af3a-41b7-b826-6c0bbdfd6a00.png)

Vista desde la app

![image](https://user-images.githubusercontent.com/71842389/201761937-b7588a06-4694-4c87-919e-6e04500c5d7c.png)

Vista desde MongoDB Compass

![image](https://user-images.githubusercontent.com/71842389/201761964-6fa45172-cc21-4a13-8ada-30b8d20c84f7.png)

**Comment by jdrodas** [comment]
Gracias @018monroz por el reporte,

Se implementó control para evitar que se registren nuevas siembras con total de hectáreas como cero o negativos. El control se visualiza de la siguiente manera:

![image](https://user-images.githubusercontent.com/29258977/205190023-a8264270-8d60-4d36-a16b-c5a2a3bf1d0a.png)

Se implementa controles adicionales en los métodos "ValidaDatosNuevaSiembra" y "ValidaDatosSiembraActualizada" en cada una de las formas "FormaNuevaSiembra" y "FormaActualizaSiembra" para evitar este comportamiento erróneo
