### ISSUE TITLE
Se requiere exportar el resultado del reporte de siembras en formato JSON

### ISSUE THREAD

**Issue by Mcestradad** [jdrodas/SiembrasMiantioquia#9]

**Comment by jdrodas** [comment]
Hola @Mcestradad, gracias por tu aporte!

He implementado en la forma de reporte de siembras registradas, tres cuadros de texto que muestran la información de la siembra en texto plano, JSON y XML:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/29258977/197305993-144fcba0-fb1e-49b9-bbfb-3e6a3d040590.png">

Se agregaron los siguientes paquetes:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/29258977/197306033-5275b9ee-1a2b-4249-b44c-79d3454a42d8.png">

Y se implementó el evento sobre el DataGridView de las siembras:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/29258977/197306105-048775e2-0afc-4c29-ae78-33b5b13719db.png">

Esto mismo se podrá implementar en el resto de las entidades.
